//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetails
    {
        public int AccountID { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
