//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetails
    {
        public int BookingID { get; set; }
        public Nullable<int> TableID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
