//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.TimeSpan> OrderTime { get; set; }
        public string FoodStatus { get; set; }
        public string DrinkStatus { get; set; }
        public string TotalPrice { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
