//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
